language: bash
services: docker

env:
  - VERSION=7.4 BASE_IMAGE=php MY_TARGET=dev BASE_IMAGE_TAG="7.4-fpm-alpine" EXTRA_TAGS="3.3"

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - "./hooks/build.sh"

after_script:
  - docker images
