#!/bin/bash

export VARS='
VERSION=7.4 BASE_IMAGE=php MY_TARGET=dev EXTRA_TAGS="dev"
VERSION=7.4 BASE_IMAGE=php MY_TARGET=prod EXTRA_TAGS="latest;prod"
VERSION=7.3 BASE_IMAGE=php MY_TARGET=dev EXTRA_TAGS=""
VERSION=7.3 BASE_IMAGE=php MY_TARGET=prod EXTRA_TAGS=""
'