#!/bin/bash
ENVS=(prod dev)
VERSIONS=(7.3 7.4 8.0)
TYPES=(cli fpm)

CALC_1=$(echo ${DOCKER_TAG} | cut -d "-" -f1)
CALC_2=$(echo ${DOCKER_TAG} | cut -d "-" -f2)
CALC_3=$(echo ${DOCKER_TAG} | cut -d "-" -f3)
CALC_4=$(echo ${DOCKER_TAG} | cut -d "-" -f4)

PHP_VERSION=7.4
PHP_TYPE=cli
APP_ENV=dev
APP_DEBUG=1
WITH_DATABASE="no"

[[ " ${VERSIONS[@]} " =~ " ${CALC_1} " ]] && PHP_VERSION="${CALC_1}"
[[ " ${TYPES[@]} " =~ " ${CALC_2} " ]] && PHP_TYPE="${CALC_2}"
[[ " ${ENVS[@]} " =~ " ${CALC_3} " ]] && APP_ENV="${CALC_3}"
[[ ${CALC_4} == "pgsql" ]] && WITH_DATABASE="yes"
[[ ${APP_ENV} == "prod" ]] && APP_DEBUG=0

docker build . \
        --build-arg \
                APP_ENV=${APP_ENV} \
                APP_DEBUG=${APP_DEBUG} \
                WITH_DATABASE=${WITH_DATABASE} \
                PHP_TYPE=${PHP_TYPE} \
                PHP_VERSION=${PHP_VERSION} \
        -t ${IMAGE_NAME}
