#!/bin/bash
ENVS=(prod dev)
VERSIONS=(7.3 7.4 8.0)
TYPES=(cli fpm)

CALC_1=$(echo ${DOCKER_TAG} | cut -d "-" -f1)
CALC_2=$(echo ${DOCKER_TAG} | cut -d "-" -f2)
CALC_3=$(echo ${DOCKER_TAG} | cut -d "-" -f3)

PHP_VERSION=7.4
PHP_TYPE=cli
APP_ENV=dev

if [[ ${DOCKER_TAG} == "latest" ]]; then
    PHP_VERSION=latest
else
    CALC_1=$(echo ${DOCKER_TAG} | cut -d "-" -f1)
    CALC_2=$(echo ${DOCKER_TAG} | cut -d "-" -f2)
    CALC_3=$(echo ${DOCKER_TAG} | cut -d "-" -f3)

    [[ " ${VERSIONS[@]} " =~ " ${CALC_1} " ]] && PHP_VERSION=${CALC_1}
    [[ " ${TYPES[@]} " =~ " ${CALC_1} " ]] && PHP_TYPE=${CALC_1}
    [[ " ${TYPES[@]} " =~ " ${CALC_2} " ]] && PHP_TYPE=${CALC_2}
    [[ " ${ENVS[@]} " =~ " ${CALC_1} " ]] && APP_ENV=${CALC_1}
    [[ " ${ENVS[@]} " =~ " ${CALC_2} " ]] && APP_ENV=${CALC_2}
    [[ " ${ENVS[@]} " =~ " ${CALC_3} " ]] && APP_ENV=${CALC_3}
fi

echo "Building: ${PHP_VERSION}-${PHP_TYPE}-${APP_ENV}"

exit
docker build . --build-arg APP_ENV=${APP_ENV} --build-arg PHP_TYPE=${PHP_TYPE} --build-arg PHP_VERSION=${PHP_VERSION} -t ${IMAGE_NAME}
